#!/bin/sh
/usr/local/bin/myweb 2>> /home/sysadmin/error.log
#/usr/local/bin/myweb 2>> /home/sysadmin/unix-dev/my_web_server/unix-dev-sys/myweb/myweb.log 
#/usr/local/bin/myweb 2>> /home/log/Documents/hub/unix-dev-sys/mywebmyweb.log
